# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
#
{
    'name': 'Usuarios Venezuela',
    'version': '1.0',
    'depends': ['base'],
    'author': 'Felipe Villamizar (Comunidad Bachaco.ve)',
    'category': 'Configuración Técnica',
    'description': """
            Bachaco-VE orgánica Libre para el fomento y uso de la tecnología como medio 
    para la emancipación de los pueblos y empoderamiento de los saberes!!! Inventamos o Erramos!!!
====================================

Para Registrar a un Usuario:
--------------------------------------------
    El Formulario de usuario le solitara los siguientes atributos adicionales:
    * Cédula de Identida (Obligatorio y Unico)
    * Telefono
    
    En una pestaña adicional le solicitara la Dirección:
    * Estado 
    * Municipio
    * Parroquia
    * Sector
    * Calle/Avenida
    * Casa/Edificio
    * Piso/Apartamento

Gestión de la Dirección:
--------------------------------------------------
    Usted dispondrá un administrador de los datos de la Dirección: 
    * Estado
    * Municipio
    * Parroquia
    
Para los programadores:
--------------------------------------------------
    Los nombres de objetos creados para la Dirección son los siguientes: 
    * Estado (res.estado)
    * Municipio (res.municipio)
    * Parroquia (res.parroquia)
     
    
    """,
    'update_xml': [
        'vistas/usuarios_venezuela_view.xml',
        'vistas/direccion.xml',
        'data/estados.xml',
        'data/municipios.xml',
        'data/parroquias.xml'
        ],
    "data" : [
         
        ],
    'installable': True,
    'active': False,
}

